version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=chvenu12
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking-network
    restart: always

  frontend:
    build:
      context: frontend/BackingManagementFrontend-main
      dockerfile: Dockerfile
    container_name: bankingapp-container
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - banking-network
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - account-service
      - transaction-service
      - discovery-server
    networks:
      - banking-network
    restart: always

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - banking-network
    restart: always

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: chvenu12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      - mysql-db
      - discovery-server
    networks:
      - banking-network
    restart: always

  account-service:
    build:
      context: ./account-service
    container_name: account-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/account_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: chvenu12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      - mysql-db
      - discovery-server
    networks:
      - banking-network
    restart: always

  transaction-service:
    build:
      context: ./transaction-service
    container_name: transaction-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/transaction_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: chvenu12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      - mysql-db
      - discovery-server
    networks:
      - banking-network
    restart: always

volumes:
  mysql-data:

networks:
  banking-network:
    driver: bridge
